### ISSUE TITLE
jira-miner can't populate JBEAP and JBPAPP

### ISSUE THREAD

**Issue by rsvoboda** [kpiwko/jira-miner#1]
I tried to populate smaller project, it worked. But it failed with JBEAP and JBPAPP
```
jira-miner populate "project in ('JBEAP')"
{"name":"jira-miner","hostname":"rs","pid":2073,"level":50,"err":{"message":"Cannot read property 'displayName' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'displayName' of undefined\n    at fieldChanges.map.change (/usr/lib/node_modules/jira-miner/lib/jira/history.js:86:28)\n    at Array.map (native)\n    at historySerie (/usr/lib/node_modules/jira-miner/lib/jira/history.js:84:30)\n    at jiraFieldDefinitions.reduce (/usr/lib/node_modules/jira-miner/lib/jira/history.js:24:32)\n    at Array.reduce (native)\n    at addHistorySeries (/usr/lib/node_modules/jira-miner/lib/jira/history.js:23:24)\n    at issues.forEach.issue (/usr/lib/node_modules/jira-miner/lib/jira/history.js:10:5)\n    at Array.forEach (native)\n    at Object.attachHistories (/usr/lib/node_modules/jira-miner/lib/jira/history.js:9:10)\n    at jira.listFields.then.fields (/usr/lib/node_modules/jira-miner/lib/jira/fetch.js:69:24)"},"msg":"Unable to rename field names in jira or to attach their histories","time":"2017-01-26T14:50:57.576Z","v":0}
{"name":"jira-miner","hostname":"rs","pid":2073,"level":50,"err":{},"query":"project in ('JBEAP')","msg":"Unable to fetch issues from JIRA","time":"2017-01-26T14:50:57.579Z","v":0}
TypeError: Cannot read property 'displayName' of undefined
    at fieldChanges.map.change (/usr/lib/node_modules/jira-miner/lib/jira/history.js:86:28)
    at Array.map (native)
    at historySerie (/usr/lib/node_modules/jira-miner/lib/jira/history.js:84:30)
    at jiraFieldDefinitions.reduce (/usr/lib/node_modules/jira-miner/lib/jira/history.js:24:32)
    at Array.reduce (native)
    at addHistorySeries (/usr/lib/node_modules/jira-miner/lib/jira/history.js:23:24)
    at issues.forEach.issue (/usr/lib/node_modules/jira-miner/lib/jira/history.js:10:5)
    at Array.forEach (native)
    at Object.attachHistories (/usr/lib/node_modules/jira-miner/lib/jira/history.js:9:10)
    at jira.listFields.then.fields (/usr/lib/node_modules/jira-miner/lib/jira/fetch.js:69:24)
```

**Comment by kpiwko** [comment]
Seems there is no author of change - maybe some automated tool does that.

This would be easy to fix.
